### ISSUE TITLE
Entity cache record destructure assigns name to version when building the no stream record

### ISSUE THREAD

**Issue by jdextraze** [eventide-project/entity-cache#4]
See https://github.com/eventide-project/entity-cache/blob/master/lib/entity_cache/record/destructure.rb#L23

**Comment by sbellware** [comment]
Ultimately, the "no stream" value is a special case value (constant) that indicates that there's actually no stream for the object in-question.

Throughout the upper levels of the toolkit that are most frequently interacted with by a user, the symbol `:no_stream` is used to represent `-1`, which is the conventional value of a stream version for a stream that doesn't exist.

Because the literal value `-1` has no symbolic meaning, we use `:no_stream` interchangeably. 

The definition of the concept of "No Stream" can be found in the MessageStore namespace (which is in the `evt-message-store` library. That definition includes the version number as well as the "name" of the no stream concept:
https://github.com/eventide-project/message-store/blob/master/lib/message_store/no_stream.rb#L4

The symbol `:no_stream` is canonized to `-1` before it's used in the raw storage layer:
https://github.com/eventide-project/message-store/blob/6aa5aaf1928e331300e5acc4b50357bf9a6505fb/lib/message_store/expected_version.rb#L5-L9

While in-general, it's undesirable to misrepresent the truth of something (`-1` is _the truth_). This is not a general case, and thus the special variation from the rule is permissible (and desirable).

So, this is as-designed. Did it cause a malfunction?

**Comment by jdextraze** [comment]
No malfunction. I am just reading the code to understand what it does. I missed the canonization part which transform the label to a number. Thanks for the explanation.

**Comment by sbellware** [comment]
Oh! Right on. Cool. Glad to help.
